### ISSUE TITLE
fix the "th" size on the tablesorter

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1061]
Hello,

is there a way to fix the size of the header "th"?

i am asking this because i have a several number of colums, and, there are columns with only a tiny simbol but the size of the field is very big, i would like to have the size of the "th" change with the size of the content of the below "td". ( i know this is not a 100% issue for Jquery tablesorter....)

**Comment by Mottie** [comment]
Hi @fcferreira29!

Do you mean the width of the header columns? The easiest solution would be to add a class to each header cell, then set the width in the CSS.

```css
.col1 { width: 2%; }
.col2 { width: 8%; }
.col3 { width: 40%; }
.col4 { width: 50%; }
```

```html
<thead>
  <tr>
    <th class="col1"></th> <!-- button -->
    <th class="col2">ID</th>
    <th class="col3">Name</th>
    <th class="col4">Description</th>
  </tr>
</thead>
```
