### ISSUE TITLE
filter widget with hidden columns

### ISSUE THREAD

**Issue by prtome** [Mottie/tablesorter#1066]
Hello
I have a problem with the filter widget and hidden columns. The widget ignores the hidden class and shows the search box for each of the hidden columns. 
Maybe I missed something in the docs. Is there a way of saying the filter is false for all, and true only for the columns I want filtered ?

thanks a lot
Pat

**Comment by Mottie** [comment]
Hi Pat!

In this situation, you can use the [`filter_cssFIlter` option](http://mottie.github.io/tablesorter/docs/example-widget-filter.html#filter-css-filter) to add a class name to the filter cell to hide it:

```css
.hidden { display: none; }
```

```js
// hiding the second & fourth columns
filter_cssFilter : [ '', 'hidden', '', 'hidden' ]
```

Really the easiest way to hide a column is to use a css selector like this:

```css
 /* hide <col> so set widths apply to correct columns*/
table col:nth-child(3),
table tr th:nth-child(3),
table tr td:nth-child(3) {
  display: none;
}
```
