### ISSUE TITLE
apply a specific class in a cell

### ISSUE THREAD

**Issue by prtome** [Mottie/tablesorter#1078]
Hello
I get the table data from a database, and when values in given cell are below a certain limit, I would like to highlight the cell.
When not using tablesorter, I put <td class="yellow-alert"> blabla </td> in the cell , and it works
when using tablesorter this does not work anymore.  I am pretty sure it is a css problem, but I cannot find what I must change, I have been trying different things without any result.
Any idea of how to define my yellow-alert (and red of course;) so it is taken and shown
Thanks
Pat

**Comment by Mottie** [comment]
Hi @prtome!

It sounds like you might be having an issue with [css specificity](https://css-tricks.com/specifics-on-css-specificity/).

If you are not using the zebra widget, this css will work on the table ([demo](http://jsfiddle.net/Mottie/856bzzeL/718/)):

```css
/* without zebra widget */
.tablesorter td.green {
    background: #006000;
    color: #fff;
}
```

If you are using the zebra widget, you'll need to increase the specificity:

```css
/* with zebra widget */
.tablesorter tbody tr td.green {
    background: #006000;
    color: #fff;
}
```
