### ISSUE TITLE
"Loading..." indicator while table is still loading and tablesorter yet to be applied

### ISSUE THREAD

**Issue by aetna-wsa** [Mottie/tablesorter#1080]
I have a table with over 1300 rows loading and I'm wondering if there is a way to display a "Loading" message or graphic that will wait until the table is loaded AND formatting is applied to the table, before showing it to the user?

**Comment by Mottie** [comment]
Hi @aetna-wsa!

Here is one method of doing it ([demo](http://jsfiddle.net/Mottie/856bzzeL/720/)):
* Wrap the table with a `div`.
* Add the theme class to the table, in this case we'll use `"tablesorter-blue"`

    ```html
    <div class="wrapper loading">
        <table class="tablesorter-blue">...</table>
    </div>
    ```
* Add some css to cover the entire table (overlay) and add a loading indicator

    ```css
    .wrapper {
      position: relative;
    }
    .loading:before {
      content: '';
      display: block;
      width: 100%;
      height: 100%;
      position: absolute;
      top: 0;
      left: 0;
      bottom: 0;
      right: 0;
      z-index: 100;
      background: rgba(0,0,0,0.3) center center no-repeat url('data:image/gif;base64,R0lGODlhFAAUAKEAAO7u7lpaWgAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQBCgACACwAAAAAFAAUAAACQZRvoIDtu1wLQUAlqKTVxqwhXIiBnDg6Y4eyx4lKW5XK7wrLeK3vbq8J2W4T4e1nMhpWrZCTt3xKZ8kgsggdJmUFACH5BAEKAAIALAcAAAALAAcAAAIUVB6ii7jajgCAuUmtovxtXnmdUAAAIfkEAQoAAgAsDQACAAcACwAAAhRUIpmHy/3gUVQAQO9NetuugCFWAAAh+QQBCgACACwNAAcABwALAAACE5QVcZjKbVo6ck2AF95m5/6BSwEAIfkEAQoAAgAsBwANAAsABwAAAhOUH3kr6QaAcSrGWe1VQl+mMUIBACH5BAEKAAIALAIADQALAAcAAAIUlICmh7ncTAgqijkruDiv7n2YUAAAIfkEAQoAAgAsAAAHAAcACwAAAhQUIGmHyedehIoqFXLKfPOAaZdWAAAh+QQFCgACACwAAAIABwALAA
    ```

* Once you finish loading the content, then initialize tablesorter & in the `initialized` callback, remove the overlay - the demo doesn't do this because it's not loading content.

    ```js
    $('table').tablesorter({
        theme: 'blue',
        initialized: function(){
            $('.wrapper').removeClass('loading');
        }
    });
    ```
