### ISSUE TITLE
how to set specific column header width

### ISSUE THREAD

**Issue by rdd992** [Mottie/tablesorter#1129]
i want to modify only the check colum width, i've tried width css  but it doesn't work
![issue](https://cloud.githubusercontent.com/assets/13080542/12421964/5a5b3ee0-bea3-11e5-9d65-43c2a8d6d755.png)

**Comment by Mottie** [comment]
Hi @rdd992!

There are two common methods to set a column width.

1) Add a class name to the header, then add css to set the width

```html
<th class="checkboxes"></th>
```

```css
.checkboxes {
  width: 20px;
}
```

2) If you don't want to add a class name, then use the `nth-child` selector:

```css
td:nth-child(1) {
  width: 30px;
  text-align: center;
}
```

[This demo](http://jsfiddle.net/Mottie/856bzzeL/825/) includes both methods, but you'll need to switch the css around.
