### ISSUE TITLE
Can add alignment setting "ts-align-center" in tbody > th ?

### ISSUE THREAD

**Issue by airthomas** [Mottie/tablesorter#1132]
hi, my current method is change the ajaxProcessing... any easier method to setup columns content alignment ?
many thanks.

**Comment by Mottie** [comment]
Hi @airthomas!

Use css ([demo](http://jsfiddle.net/Mottie/856bzzeL/839/)):

```css
td:nth-child(2) {
  text-align: center;
}
```
