### ISSUE TITLE
Header name and desc/asc symbols overlaps

### ISSUE THREAD

**Issue by innc** [Mottie/tablesorter#12]
Hello :)

I have noticed the following issue, if you reduce much the width of the browser, then header name and desc/asc symbols will overlap. In my opinion this doesn't look nice.

Picture example for blue skin:
http://s7.directupload.net/file/d/2732/niutsquo_jpg.htm

Picture example for cupertino UI theme style:
http://s14.directupload.net/file/d/2732/85bunm8q_jpg.htm

One possible solution for the blue skin would be this:

Add at style.css of the Blue Skin:

``` css
table.tablesorter thead tr th, tr.stickyHeader th, table.tablesorter tfoot tr th 
{
    background-color: #e6eeee;
    border-collapse: collapse;
    font-size: 8pt;
    padding: 4px;
    padding-right: 20px;  /* NEW LINE */
}
```

Unfortunately this solution doesn't seem to work for Cupertino UI theme style.
I added same new line to style.css like the css code at http://mottie.github.com/tablesorter/docs/example-widget-ui-theme.html

``` css
table.tablesorter thead tr th, table.tablesorter tfoot tr th 
{
    border-collapse: collapse;
    font-size: 8pt;
    padding: 4px;
    padding-right: 20px; /* NEW LINE */
}
```

But no effect...
