### ISSUE TITLE
Change text-align for specific colum

### ISSUE THREAD

**Issue by gagarin77** [Mottie/tablesorter#1241]
Hi
in thi site  i have insert the table  with tablesorter. Now i can change text-align
for colum "squadra di casa" and "squadra ospite" i create in html code a special class
"calendTname" for thios colum

i have insert this rule in my css file   (jsportdap)
.calendTname td {
text-align:left;
}
but not working and the text remain in center position

the link for site is here 
http://lullonehockeyclub.joomlafree.it/index.php?option=com_joomsport&view=matchday&id=1&Itemid=1100

thanks for you help

**Comment by Mottie** [comment]
Hi @gagarin77!

The css rule isn't working because of the `td` has a class name of `calendTname`; and also because of [CSS specificity](https://css-tricks.com/specifics-on-css-specificity/). If you right click and inspect a cell in that column, you'll see this definition is set to center align the text

```css
#fixed-columns-table tbody td {
    /* other definitions */
    text-align: center;
}
```

Increase the CSS specificity of your definition. Maybe try something like this:

```css
#fixed-columns-table tbody td.calendTname {
  text-align:left;
}
```

Also, there are a bunch of errors on that page. The tablesorter related one is the the date parser which needs to be moved *below* the script that loads tablesorter:

```html
<script src="table-master/js/jquery.tablesorter.js"></script>
<script src="table-master/js/parsers/parser-date.js"></script>
```
