### ISSUE TITLE
put image into column header

### ISSUE THREAD

**Issue by therise03** [Mottie/tablesorter#1266]
Hi, I am new to this great plugin. What I am trying to do is add a small magnifying glass icon to the left of my first column. Though I am not sure how to achieve this since it seems the filter text inputs are generated dynamically. Any help would be highly appreciated! Thanks!!

**Comment by Mottie** [comment]
Hi @therise03!

Try this code ([demo](http://jsfiddle.net/Mottie/bbxxomhx/91/)):

CSS ([from here](http://google.github.io/material-design-icons/))

```css
@import 'https://fonts.googleapis.com/icon?family=Material+Icons';
.material-icons {
  vertical-align: middle; /* added to align with input */
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  /* Preferred icon size */
  display: inline-block;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: ltr;
  /* Support for all WebKit browsers. */
  -webkit-font-smoothing: antialiased;
  /* Support for Safari and Chrome. */
  text-rendering: optimizeLegibility;
  /* Support for Firefox. */
  -moz-osx-font-smoothing: grayscale;
  /* Support for IE. */
  font-feature-settings: 'liga';
}
```

JS

```js
$(function() {
  $('table')
    .on('filterInit', function() {
      var $cell = this.config.$filters.eq(0);
      $cell.prepend('<i class="material-icons">search</i>');
      $cell.find('input').css('width', '80%');
    })
    .tablesorter({
      theme: 'blue',
      widgets: ['zebra', 'filter']
    });
});
```

**Comment by therise03** [comment]
thanks sir this was great! I am using bootstrap so my only concern is, is there a way to keep this and the text field in the column header aligned left? And maybe even a no-wrap col header so the icon doesnt stack when the cell gets to small? mmm might be asking for lot here.

**Comment by Mottie** [comment]
Sorry for not replying sooner. Maybe use css to prevent wrapping? ([demo](http://jsfiddle.net/Mottie/bbxxomhx/137/))

```css
.tablesorter-filter-row td:first-child {
  white-space: nowrap;
  overflow: hidden;
}
```

The main issue would be the input would overflow to the right and hide some of the internal text.
