### ISSUE TITLE
Stickyheaders IE and Chrome

### ISSUE THREAD

**Issue by mtgtnt** [Mottie/tablesorter#1291]
I'm back :(

I am unable to find a solution to the the sticky header incorrectly aligning in IE and Chrome. FF is fine.
See http://jsbin.com/kumanimuli/1/edit?output

I have tried a wrapper div but it did not help. It seems something with it incorrectly calculating left when margin auto, but im only guessing now. It's all looking like a big blob of text now after 6 hours of trying a multitude of options.

I am also unable to find how to keep the background arrow images to also show in the sticky. You will see this in the jsbin.

ps. I tried to use jsfiddle but it wont load in my IE so i had to resort to jsbin.

**Comment by Mottie** [comment]
Hi @mtgtnt!

The main issue is the `margin: auto` shouldn't be applied to the table. Instead apply it to the outer wrapper and make sure to set a width

```css
#contacts {
  margin: 0 auto; /* removed from .pivot definition */
  width: 1255px;
}
```

Because the main table has an ID, the background arrows are only being applied to the main table through css. The cloned header will also have an ID, but to keep it unique, a "-sticky" is added to the end (see the [stickyHeaders_cloneId](https://mottie.github.io/tablesorter/docs/index.html#widget-sticky-headers-cloneid) option). This also needs a css update:

```css
#sortcontacts thead, #sortcontacts-sticky thead {
  cursor: pointer;
}
#sortcontacts thead th.up, #sortcontacts-sticky thead th.up { ... }
#sortcontacts thead th.down, #sortcontacts-sticky thead th.down { ... }
```

No changes to the javascript are needed. That should get everything working - see [updated demo](http://jsbin.com/doqoboqahi/edit?output).
