### ISSUE TITLE
StickyHeaders on Left Menu

### ISSUE THREAD

**Issue by airthomas** [Mottie/tablesorter#1368]
Hi,

I'm not sure it is a bug or not, would you please give some ideas to me, many many thanks.

http://jsfiddle.net/abkNM/9100/
reproduce steps:
1) scroll down until stickyheaders
2) click left-top icon to hide Left Menu
3) the stickyheaders will NOT scroll

Many thanks.

**Comment by airthomas** [comment]
I applied stickyheaders class and changing offset in jquery, then the problem has solved. Many thanks.

**Comment by Mottie** [comment]
Hi @airthomas!

I saw the demo a few days ago, and today it looks different and the left menu isn't opening... anyway, I think the easiest fix would be to also add the "open" class to the content element, and use something like this ([demo](http://jsfiddle.net/abkNM/9110/) not working):

```css
.FW_LeftMenu.close,
.FW_Content.close .tablesorter-sticky-wrapper {
  margin-left: -150px;
}
```

**Comment by airthomas** [comment]
Hi Mottie,

I have tried, but would you please try below steps, since the stickyheaders will slide to left due last scrolling...

1) scroll down until stickyheaders
2) click left-top icon to hide Left Menu
3) the stickyheaders will slide to left (good)
4) scroll up or down, the stickyheaders will slide again to left again (bad)

sorry my bad english and hope you can understand. Many thanks.

**Comment by airthomas** [comment]
Hi, another feature is when the browser change to smaller than 717px, the TopMenu will change position: from fixed to relative;, means the TopMenu will scroll up, can the stickyheaders dynamic change the stickyHeaders_offset from 40 to 0 ? many thanks.

**Comment by Mottie** [comment]
try this ([demo](http://jsfiddle.net/Mottie/abkNM/9127/)):

Script

```js
$(function() {
  $('.FW_LeftMenuToggle').click(function() {
    if ($(window).width() <= 700) {} else {
      var dir = $('.FW_LeftMenu').hasClass('close');
      $('.FW_LeftMenu, .FW_Content, .FW_ButtonBar, .FW_UserMessageBar, .FW_SearchBar').toggleClass('close');
      stickySlide(dir);
    }
  });
  $('.FW_Content').click(function() {
    CloseAllPopUp();
  });
  $(window).scroll(function() {
    $('.FW_UserPopup').fadeOut();
  });

  function stickySlide(toggle) {
    var direction = toggle ? 'open' : 'close';
    $('.tablesorter-sticky-wrapper').addClass(direction);
    setTimeout(function() {
      $('.tablesorter-sticky-wrapper').removeClass(direction);
      $(window).scroll();
    }, 500);
  }

  function CloseAllPopUp() {
    if ($(window).width() <= 1300) {
      $('.FW_LeftMenu, .FW_Content').removeClass('open');
      stickySlide(dir);
    }
  }
});

$('table').tablesorter({
  theme: 'blue',
  widthFixed: true,
  widgets: ['zebra', "stickyHeaders"],
  widgetOptions: {
    zebra: [
      "ui-widget-content even",
      "ui-state-default odd"
    ],
    stickyHeaders_offset: '40px',
    saveSort: true,
    stickyHeaders: "tablesorter-stickyHeader"
  }
});
```

CSS changes

```css
	.FW_LeftMenu.open,
	.tablesorter-sticky-wrapper {
	  margin-left: 0;
	}
	
	.FW_LeftMenu.close,
	.tablesorter-sticky-wrapper.close {
	  transition: margin-left 0.4s ease-in-out 0s;
	  margin-left: -150px;
	}
	
	.tablesorter-sticky-wrapper.open {
	  transition: margin-left 0.4s ease-in-out 0s;
	  margin-left: 150px;
	}

	@media all and (max-width: 717px) {
	  .tablesorter-sticky-wrapper {
	    margin-top: -40px;
	  }
	}
```

**Comment by airthomas** [comment]
Thanks Mottie, it looks very very good now.

Only the UI will occur below if .tablesorter-sticky-wrapper's margin-top changed to -150.
![image](https://cloud.githubusercontent.com/assets/4132152/23844352/893fac8e-07fc-11e7-9807-262a9f3e0995.png)

**Comment by airthomas** [comment]
Hi Mottie,

Base on your demo (http://jsfiddle.net/Mottie/abkNM/9127/), when all data are display on screen, the vertical scroll bar still exist like below...

![image](https://cloud.githubusercontent.com/assets/4132152/24247073/1ca1bb56-1005-11e7-9922-0b7fcfb9ba29.png)


Many thanks your help.

**Comment by Mottie** [comment]
Hi @airthomas!

Was that last comment a question? I wouldn't base the layout on the jsFiddle because everything is inside of iframes. Does it look okay on your web site?

**Comment by airthomas** [comment]
Hi Mottie,

Sorry for late reply, just remain below issue on thin screen.

![image](https://cloud.githubusercontent.com/assets/4132152/24710929/24e2c9da-1a51-11e7-9c21-54ffb75cd510.png)

*the stickyheaders duplicated after added below
       @media all and (max-width: 717px) {
	  .tablesorter-sticky-wrapper {
	    margin-top: -40px;
	  }
	}

Others are worked perfect.

Many thanks your help !

**Comment by Mottie** [comment]
Oh... if you change the calculated height of the left bar and wrapper, the scrollbar won't appear ([demo](http://jsfiddle.net/Mottie/abkNM/9225/))

```css
.FW_LeftMenu, .FW_Content {
  height: calc(100vh - 45px);
}
```

\* You don't need all the vendor prefixes anymore

Other than that, has this issue been resolved?
