### ISSUE TITLE
Feature Request: Add Class to filter row when filter applied

### ISSUE THREAD

**Issue by Lopton** [Mottie/tablesorter#1429]
I have looked through all the documentation for this and don't think it exists. I would like to style the filter row or cell when a filter is applied. 

Currently the filter applies, but there is no significant visual warning to the user that there is a filter in place. I just want to apply a CSS class to the row or the cell in the filter row that is currently filtering as reminder to the user that a filter is in place.

Thanks!

**Comment by Mottie** [comment]
Hi @Lopton!

You can add a binding to the "filterStart" event and use the `filters` value it provides to add classes to the filter cells - [demo](https://jsfiddle.net/Mottie/bbxxomhx/478/):

```css
/* filter cell is styled using
 * .tablesorter-blue .tablesorter-filter-row td, so we 
 * need to use a higher css specificity to override it
 */
table .tablesorter-filter-row td.filter-active {
  border-bottom-color: red;
}
```

```js
$(function() {
  var active = "filter-active";

  $('table')
    .on('filterStart', function(e, filters) {
      var $cells = $(this).find('.tablesorter-filter-row td');
      $cells.filter('.' + active).removeClass(active);
      $.each(filters, function(i, val) {
        if (val !== "") {
          $cells.eq(i).addClass(active);
        }
      });
    })
    .tablesorter({
      theme: 'blue',
      widgets: ['zebra', 'filter']
    });
});
```
