### ISSUE TITLE
cssStickyHeaders content overlaps header

### ISSUE THREAD

**Issue by otakueadwine** [Mottie/tablesorter#1453]
Hi! First of all thank you for the plugin ;) I'm trying to make use of the cssStickyHeaders widget, but somehow the content keeps overlapping the header. It seems to be a z-index issue, but when I try to overrule the styling of any of the elements, I cannot get it to work properly. Is this a bug or is there something I'm doing wrong? 

![image](https://user-images.githubusercontent.com/8110976/30023829-6aee6834-9171-11e7-8309-6c8934fcfb34.png)

                table.tablesorter({
                    widgets: [ 'cssStickyHeaders' ],

                    widgetOptions: {
                        cssStickyHeaders_attachTo      : $(this).find('.panel-data'),
                        cssStickyHeaders_zIndex: 9999
                    }
                });

![image](https://user-images.githubusercontent.com/8110976/30024799-b6b3ebdc-9175-11e7-9a50-65f5ca78ccc2.png)

**Comment by Mottie** [comment]
Hi @otakueadwine!

It looks like you're using a custom theme. In that case, you'll need to add a background color to the `th` and if you're including borders, you'll need to add that to the inner block. I set up [this demo](https://jsfiddle.net/Mottie/f36416oy/46/) with the following custom css:

```css
table {
  width: 100%;
  border-collapsed: collapsed;
  border-spacing: 0;
}
table, td, caption {
  border: 1px solid #ddd;
  padding: 2px 4px;
}
th {
  padding: 0;
}
.tablesorter-header-inner {
  border: 1px solid #ddd;
  border-width: 0 1px 0 0;
  padding: 2px 4px;
}
.tablesorter-header-inner:first-child {
  border-left-width: 1px;
}
th, thead, caption {
  background: #eee;
}
```
