### ISSUE TITLE
Bottom Scroll Bar on 125% system font

### ISSUE THREAD

**Issue by MoMack20** [Mottie/tablesorter#1474]
![image](https://user-images.githubusercontent.com/11836187/32174026-1f68cf5a-bd57-11e7-9855-5cfc99e0f69b.png)

There are some computers where the system default font size is 125% and it results in a horizontal scrollbar almost always being present when there is a vertical scrollbar. It is normal on a 100% default text computer. Is there any way around this?

**Comment by Mottie** [comment]
Hi @MoMack20!

Hmm, try this:

```css
@media (min-resolution: 110dpi) and (max-resolution: 120dpi) {
  table {
    overflow-x: hidden;
  }
}
```

It's not ideal, especially if the table is overflowing and you need the scrollbars; we might need some javascript to check the `window.devicePixelRatio` (at `1.25`) and then compare the table and container widths, and hide the overflow if it's within a certain tolerance.
