### ISSUE TITLE
Zebra widget and childRow's

### ISSUE THREAD

**Issue by zod6** [Mottie/tablesorter#1501]
Hi!
Is it possible to add zebra stripes to childrows? Couldn't find any way to do it. It adds only "odd" or "even" to all sub-row <tr> elements.
Example is here: http://jsfiddle.net/9b1y463k/3/

**Comment by Mottie** [comment]
Hi @zod6!

You can use the CSS `:nth-child()` selector to accomplish that ([demo](http://jsfiddle.net/Mottie/9b1y463k/4/)):

```css
.tablesorter tr.tablesorter-childRow:nth-child(2n) > td { background-color: #AFCB83; }
.tablesorter tr.tablesorter-childRow:nth-child(2n + 1) > td { background-color: #BCF0D9; }

.tablesorter .toggle.odd td { background-color: #C0B784; font-weight: bold; }
.tablesorter .toggle.even td { background-color: #DDDDDA; font-weight: bold; }
```
