### ISSUE TITLE
Vertical Scroll on single column

### ISSUE THREAD

**Issue by LivC182** [Mottie/tablesorter#1561]
Hi,
I have a table with n column. n-1 of them have a height of max 300px the last one is very big more than 1000px each. I was wondering if I can put a scroll bar on just the nth column

**Comment by Mottie** [comment]
Hi @LivC182!

It sounds like the last column doesn't include data that could be associated with the first n-1 columns. Maybe it would work better to have two separate tables next to each other. Try this layout ([demo](https://jsfiddle.net/bbxxomhx/1373/)):

HTML

```html
<div class="wrapper">
  <table id="short-table">...</table>
  <div class="tall-table">
    <table id="tall">...</table>
  </div>
</div>
```

CSS

```css
.wrapper {
  display: flex;
  flex: 1 1 auto;
}
.tall-table {
  width: 150px;
  height: 300px;
  overflow-y: auto;
}
```
