### ISSUE TITLE
zebra stripe rows with more than 2 colors

### ISSUE THREAD

**Issue by dmikester1** [Mottie/tablesorter#1587]
Is it possible to zebra stripe rows with more than 2 colors?  Say repeat color ever third or fourth rows?

**Comment by Mottie** [comment]
Hi @dmikester1!

If you're not using the filter widget, then you can use basic css to stripe the rows ([demo](https://jsfiddle.net/Mottie/bbxxomhx/1761/)):

```css
table tr:nth-child(3n) td {
  background: blue;
  color: white;
}
table tr:nth-child(3n+1) td {
  background: red;
  color: white;
}
table tr:nth-child(3n+2) td {
  background: green;
  color: white;
}
```

Or if you are using the filter widget, you'll need a custom zebra striper ([demo](https://jsfiddle.net/Mottie/jmywp5b9)):

```css
.blue td {
  background: blue;
  color: white;
}
.red td {
  background: red;
  color: white;
}
.green td {
  background: green;
  color: white;
}
.purple td {
  background: purple;
  color: white;
}
```

Note: I added a 4th color, but you can remove it from the `widgetOptions`... it will adjust the striping by the length of the `zebraN` array.

```js
$(function() {
	$.tablesorter.addWidget({
  	id: 'zebraN',
    options: {
    	zebraN: ['white', 'grey']
    },
    format: function(table, c, wo) {
    	var zebraN = wo.zebraN.length,
      	$rows = c.$tbodies.children().filter(':visible');
      for (var i = 0; i < $rows.length; i++) {
      	$rows.eq(i)
        	.removeClass(wo.zebraN.join(' '))
        	.addClass(wo.zebraN[ i % zebraN ])
      }
    }
  });

  $('table').tablesorter({
    theme: 'blue',
    widgets: ['zebraN'],
    widgetOptions: {
    	// class names to add
    	zebraN: ['red', 'green', 'blue', 'purple']
    }
  });
});
```
