### ISSUE TITLE
Override tr / td color

### ISSUE THREAD

**Issue by ciadch** [Mottie/tablesorter#1591]
Hi @Mottie,

Is there a way to override the color of tr/td when zebra widget is used ? I really need to use bootstrap colors on certain tr/td but it's seems it's not possible when zebra is used !

Thanks for your help !

**Comment by Mottie** [comment]
Hi @ciadch!

Because the built-in css themes have a really high css specificity, to allow nested tables to have a different theme, you'll need to add an even higher specificity selector to restore the background colors ([demo](https://jsfiddle.net/Mottie/z8Lacguz/163/)):

```css
.tablesorter-bootstrap:not(.table-dark) > tbody > tr.even > td.alert-danger,
.tablesorter-bootstrap:not(.table-dark) > tbody > tr.odd > td.alert-danger{
 background-color: #f8d7da; 
}

.tablesorter-bootstrap:not(.table-dark) > tbody > tr.even > td.alert-warning,
.tablesorter-bootstrap:not(.table-dark) > tbody > tr.odd > td.alert-warning {
  background-color: #fff3cd;
}

.tablesorter-bootstrap:not(.table-dark) > tbody > tr.even > td.alert-success,
.tablesorter-bootstrap:not(.table-dark) > tbody > tr.odd > td.alert-success {
  background-color: #d4edda;
}
```
