### ISSUE TITLE
Column hide width on the first load

### ISSUE THREAD

**Issue by Flom42** [Mottie/tablesorter#1692]
For one of my table I need to hide the first column of a table so I have set "display:none" to the TH and TD. But I still have some weird column size. Is because of the tablesorter.js code.

Method fixColumnWidth 
the overallWidth have at least sum the visible columns and not the total width of the table. With the total witdh the percent is false. Take 3 columns 100px width each et hide the first, you will avec 33,3% and not 50%.

A quick fix

overallWidth = 0;
$tbodies.each(function () {
overallWidth += $(this).width();
});

**Comment by Mottie** [comment]
Hi @Flom42!

Try this CSS ([demo](https://jsfiddle.net/Mottie/bbxxomhx/1996/)):

```css
table thead tr th:first-child,
table colgroup col:first-child,
table tbody tr td:first-child {
  display: none;
}
```

**Comment by Flom42** [comment]
Hi,

Yes It maye work but I reuse this view for an other pourpose (one with and one without the column) so the answer will be some javascript if.

**Comment by Mottie** [comment]
What about adding a class name to the table to apply the above css?

```css
table.hide-first-column thead tr th:first-child,
table.hide-first-column colgroup col:first-child,
table.hide-first-column tbody tr td:first-child {
  display: none;
}
```
