### ISSUE TITLE
filter_formatter don't hide with filter hide

### ISSUE THREAD

**Issue by cspeerly** [Mottie/tablesorter#250]
The filter_formatter functions don't hide using filter_hideFilters:true
The baxic Filters and select hide but not the formatter filters.

here is the jsfiddle example http://jsfiddle.net/cspeerly/zbg2r/

Also I had to change this in the formatter css file to enlarge the text on the slider flags
From 0.5em to 1em

``` css
/**** Sliders ****/
/* shrink the ui sliders to look nicer inside of a table cell */
.ui-slider {
    width: 90%;
    margin: 12px auto 2px auto; /* add enough top margin so the tooltips will fit */
    font-size: 1em;
}
```

I also added this so the range slider will resize if the column is resizable

``` css
.range {
    width: 90%;
    margin: 12px auto 2px auto; /* add enough top margin so the tooltips will fit */
    font-size: 1em;
}
```
