### ISSUE TITLE
Exclude/skip column from being sorted for all rows 

### ISSUE THREAD

**Issue by vishal-chhabria** [Mottie/tablesorter#616]
Hi Mottie,
I am using tablesorter plugin and its working great for me but in some of the tables I have row num field and the problem is that plugin sorts this field as well and i havent found anything to skip a particular column from being sorted except for a hack where in we can overwrite values after sorting is completed and the code for it is 

```
var index = jQuery('table.tablesorter').find('th#index').index();
if (index !== -1) {
    $.tablesorter.addWidget({
        id: "indexColumn",
        format: function(table) {
            for(var i=1; i <= table.tBodies[0].rows.length; i++) {
                $("tbody tr:eq(" + (i - 1) + ") td:eq(" + 0 + ")",table).html(i);
            }
        }
    });
}
```

But the problem with this code is that it is not generic, for example if want to do indexing alphabetically (a,b,c....) then this code wont help.

So can you please enhance the code to skip particular column or suggest any other method to make this happen.

Thanks in advance.

**Comment by HackToday** [comment]
@Mottie  The above way just two tables, it is not tablesorter itself support, I think

**Comment by Mottie** [comment]
Hi @HackToday!

I'm not sure I understand your question. Do you want to apply the the same locked column to two tables? If that is the case, you don't need to change any of the code in the first example... add a second table to the HTML ([demo](http://jsfiddle.net/Mottie/abkNM/8731/)).

**Comment by HackToday** [comment]
No @Mottie You example is not really one table.(and can lock one column and allow other column sort)

You use two tables, first, in some cases, we use pagination, and some automatic width so two tables is difficult for layout design and it can not have a good look as just one table

**Comment by Mottie** [comment]
There are two demos above... the first demo is one table with the first column modified via the widget. The second demo has two tables aligned horizontally to appear as one table.

In the demo I shared for you, that is a demo of two tables, each using the widget to lock a column. There are no extra tables floating to appear as a locked column.

**Comment by HackToday** [comment]
The second demo  http://jsfiddle.net/Mottie/e3V9V/51/ can not work wells for as second table can (if use bootstrap table class) the width and height can change dynamically. Left table change can cause right table align in mess

The second demo seems a way to work

**Comment by Mottie** [comment]
Ok, then try this ([demo](http://jsfiddle.net/Mottie/e3V9V/219/))

HTML (wrap each table with a div)

```html
<div>
  <div class="left-column">
    <table class="left table table-bordered table-striped">
      <thead><!-- ... --></thead>
      <tbody><!-- ... --></tbody>
    </table>
  </div>
  <div class="right-columns">
    <table class="tablesorter">
      <thead><!-- ... --></thead>
      <tbody><!-- ... --></tbody>
    </table>
  </div>
</div>
```

```css
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}

.left-column {
  width: 28px;
  float: left;
  overflow: hidden;
}
.left-column table {
  float: right;
}
.left-column th {
  font-weight: bold;
  height: 45px;
}
.left-column thead {
  background-color: #efefef;
}

.right-columns {
  width: calc(100% - 28px);
  float: left;
}

table {
  display: inline-block;
}
```
