### ISSUE TITLE
tfoot > td recive tablesorter-headerAsc class on sort

### ISSUE THREAD

**Issue by fsantana** [Mottie/tablesorter#792]
When sort a column, the cell that is inside tfoot receives the class of cell thead.

To view, go to this link and sort the last column:
http://jsfiddle.net/vCTHw/1097/

Sorry for bad English.

**Comment by Mottie** [comment]
Hi @fsantana!

Yes, that was intentional. If you use the provided [`theme.blue.css` file](https://github.com/Mottie/tablesorter/blob/master/css/theme.blue.css), you'll notice that the css removes the background sorting arrow in the tfoot.

```css
/* tfoot */
.tablesorter-blue tfoot .tablesorter-headerSortUp,
.tablesorter-blue tfoot .tablesorter-headerSortDown,
.tablesorter-blue tfoot .tablesorter-headerAsc,
.tablesorter-blue tfoot .tablesorter-headerDesc {
	/* remove sort arrows from footer */
	background-image: none;
}
```
