### ISSUE TITLE
Applying an filter by selecting option (filter-select) neglects tablesorter-childRow

### ISSUE THREAD

**Issue by xxxmdnxxx** [Mottie/tablesorter#821]
If an option of an `filter-select` is selected, the filter applies to parent rows (`tablesorter-hasChildRow`) only and leaves all `tablesorter-childRow` unfiltered (_visible_).
```html
<th class="filter-select">PO</th>
```

You can reproduce this bug by running the following jsFiddle and selecting any value from _PO_-Filter:
http://jsfiddle.net/os7hyevy/

Filtering by regular search-boxes handles `tablesorter-childRow` as expected.

**Comment by Mottie** [comment]
Hi @xxxmdnxxx!

Since that demo isn't using one of the provided themes, you'll need to include this bit of css ([ref](https://github.com/Mottie/tablesorter/blob/master/css/theme.blue.css#L215-L218)) to make that demo behave properly ([updated demo](http://jsfiddle.net/Mottie/os7hyevy/1/)):

```css
/* rows hidden by filtering (needed for child rows) */
.tablesorter .filtered {
	display: none;
}
```
