### ISSUE TITLE
Grey overlay for fixed columns

### ISSUE THREAD

**Issue by Francks11** [Mottie/tablesorter#887]
Hello @Mottie,

I suggest you an improvement for "Fixed Columns" : Add a grey overlay over the fixed columns to 
better see the fixed columns.

You can see a demo here : http://jsfiddle.net/856bzzeL/172/

I added the necessary code in scroller widget javascript file.

At the beginning of the file :
```
$.extend( ts.css, {
...
	scrollerLayer  : 'tablesorter-scroller-layer',
...
});
```
Add options :

```
	options : {
		...
		// overlay on fixed columns
		scroller_overlay : true
	},
```
Add css in style
```
	var style = '<style>' +
		...
		/* add overlay */
		'.' + tscss.scrollerWrap + ' .' + tscss.scrollerLayer + ' { background-color: grey; z-index: 2; opacity: 0.15 }' +
		'</style>';
	$( style ).appendTo( 'body' );
```
At the end of updateFixed :

```
		if( wo.scroller_overlay ) {
			
			// add fixed columns grey overlay
			$( "." + tscss.scrollerLayer ).remove();
			$( "." + tscss.scrollerWrap ).append( $( "." + tscss.scrollerFixed ).clone().empty().addClass( tscss.scrollerLayer ) );
		}
```

Can you integrate it in next version?

Thank you.

**Comment by Mottie** [comment]
Hi @Francks11!

In the next version, the pointer events will be restored in the fixed column to allow better interaction with elements. Adding an overlay would again prevent this interaction.

I think the best solution would be to add some simple css ([demo](http://jsfiddle.net/856bzzeL/173/)):

```css
.tablesorter-scroller .tablesorter-scroller-fixed .tablesorter tbody tr td {
    filter: brightness(0.95);
    -webkit-filter: brightness(0.95);
}
```

Or, if you care about older IE, then maybe change the opacity:

```css
.tablesorter-scroller .tablesorter-scroller-fixed .tablesorter tbody tr td {
    opacity: 0.8;
    -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
}
```

I don't think it looks as good, so maybe add a mixture of both and change the brightness for modern browsers and opacity for older IE.
