### ISSUE TITLE
tablesorter-childRow cursor highlights 3 rows

### ISSUE THREAD

**Issue by southmeadows** [Mottie/tablesorter#893]
I have multiple child rows which works great. When you put the cursor on the child rows it highlights 3 rows at a time. 

What do I need to change to make it only high light one row?

**Comment by Mottie** [comment]
Hi @southmeadows!

Every css theme file has definitions similar to this ([blue theme example](https://github.com/Mottie/tablesorter/blob/master/css/theme.blue.css#L96-L115)):

```css
/* hovered row colors
 you'll need to add additional lines for
 rows with more than 2 child rows
 */
.tablesorter-blue tbody > tr.hover > td,
.tablesorter-blue tbody > tr:hover > td,
.tablesorter-blue tbody > tr:hover + tr.tablesorter-childRow > td,
.tablesorter-blue tbody > tr:hover + tr.tablesorter-childRow + tr.tablesorter-childRow > td,
.tablesorter-blue tbody > tr.even.hover > td,
.tablesorter-blue tbody > tr.even:hover > td,
.tablesorter-blue tbody > tr.even:hover + tr.tablesorter-childRow > td,
.tablesorter-blue tbody > tr.even:hover + tr.tablesorter-childRow + tr.tablesorter-childRow > td {
	background-color: #d9d9d9;
}
.tablesorter-blue tbody > tr.odd.hover > td,
.tablesorter-blue tbody > tr.odd:hover > td,
.tablesorter-blue tbody > tr.odd:hover + tr.tablesorter-childRow > td,
.tablesorter-blue tbody > tr.odd:hover + tr.tablesorter-childRow + tr.tablesorter-childRow > td {
	background-color: #bfbfbf;
}
```

Just remove them.
