### ISSUE TITLE
Conflict between scroller and columnSelector widgets

### ISSUE THREAD

**Issue by fab-girard** [Mottie/tablesorter#967]
Hello,
I'm trying to use these 2 widgets but unfortunately with conflict.
Here the demo :
http://jsfiddle.net/sLazbL1z/

Observe the result : 
- columns from thead and tbody are not aligned
- if you resize the window (shorter width) an horizontal scrollbar appears (only vertical should appear according to me)
- the columnSelector dropdown menu cannot be used

Regards,
Fabien

**Comment by Mottie** [comment]
Hi @fab-girard!

First off, the jQuery version is set to `jQuery (edge)`, which is jQuery v3.0.0-alpha1 and it always seems to act weird for me when it comes to measuring widths. So, I switched [the demo](http://jsfiddle.net/Mottie/sLazbL1z/2/) to use the more stable `jQuery 2.1.3`.

To make the columnSelector dropdown menu visible, add a z-index to `.columnSelector` definition:

```css
.columnSelector {
    width: 120px;
    position: absolute;
    top: 30px;
    padding: 10px;
    background: #fff;
    border: #99bfe6 1px solid;
    border-radius: 5px;
    z-index: 100;
}
```
