### ISSUE TITLE
Is it possible to only show up and down arrows without using a whole theme?

### ISSUE THREAD

**Issue by darkred** [Mottie/tablesorter#990]
I've made [this userscript](https://greasyfork.org/en/scripts/5751-metal-archives-discography-pages-reviews-column-split-and-sortable-tables).

(Among other things) It uses your great tablesorter fork (thank you!) to make the tables in all discography tabs sortable . 
i.e. it just executes this to make the tables sortable:

```
function sorting(){
    $('.display.discog').tablesorter();  
}
```

The table sorts fine but the arrows don't show.

I know that by adding something like the following line to my script:
`$('body').append('<link rel="stylesheet" type="text/css" href="http://tablesorter.com/themes/green/style.css">');`
I could load one of tablesorter's [themes](https://mottie.github.io/tablesorter/docs/themes.html) - they are also contained in the [ZIP download](https://github.com/Mottie/tablesorter/archive/master.zip)-
but I don't want to do that.

Would it be possible to only insert 'up' and 'down' arrows in each column header <ins>without using a whole tablesorter theme</ins>, i.e. **to only use the arrow icons (from the theme) while keeping the site's style for the tables intact**?

**Comment by Mottie** [comment]
Hi @darkred!

Yeah, you don't need any theme at all... [here is a demo](http://jsfiddle.net/Mottie/856bzzeL/595/) using the following:

Script

```js
$(function () {
	$('table').tablesorter({
		cssAsc: 'up',
		cssDesc: 'down'
	});
});
```

```css
table, td, th {
    border: 1px solid black;
    border-collapse: collapsed;
    padding: 2px 5px;
}
thead th {
    background-repeat: no-repeat;
    background-position: right center;
}
thead th.up {
    padding-right: 20px;
    background-image: url(data:image/gif;base64,R0lGODlhFQAEAIAAACMtMP///yH5BAEAAAEALAAAAAAVAAQAAAINjI8Bya2wnINUMopZAQA7);
}
thead th.down {
    padding-right: 20px;
    background-image: url(data:image/gif;base64,R0lGODlhFQAEAIAAACMtMP///yH5BAEAAAEALAAAAAAVAAQAAAINjB+gC+jP2ptn0WskLQA7);
}
```
